import React from 'react';
import { 
  Building2, 
  Users, 
  Clock, 
  Euro, 
  Lock, 
  Unlock, 
  CheckCircle2, 
  AlertTriangle,
  ArrowRight,
  TrendingUp,
  ShieldCheck,
  CalendarDays,
  Rocket,
  Scale,
  Zap,
  Briefcase,
  Globe,
  GraduationCap,
  HardHat,
  Laptop,
  Plane,
  Leaf,
  Activity,
  Landmark,
  Cpu,
  MapPin,
  Building,
  Flag,
  X,
  Copy,
  Info
} from 'lucide-react';

export const Icons = {
  Building: Building2,
  Users: Users,
  Clock: Clock,
  Euro: Euro,
  Lock: Lock,
  Unlock: Unlock,
  Check: CheckCircle2,
  Alert: AlertTriangle,
  ArrowRight: ArrowRight,
  Trend: TrendingUp,
  Shield: ShieldCheck,
  Calendar: CalendarDays,
  Rocket: Rocket,
  Scale: Scale,
  Zap: Zap,
  Briefcase: Briefcase,
  Globe: Globe,
  Education: GraduationCap,
  Construction: HardHat,
  Laptop: Laptop,
  Plane: Plane,
  Leaf: Leaf,
  Pharma: Activity,
  Bank: Landmark,
  Cpu: Cpu,
  Location: MapPin,
  Office: Building,
  Flag: Flag,
  Close: X,
  Copy: Copy,
  Info: Info
};